# Generated by Django 3.0.8 on 2020-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=30, verbose_name='歌曲名')),
                ('song_id', models.CharField(max_length=15, verbose_name='歌曲id')),
                ('comment', models.TextField(verbose_name='热评内容')),
                ('comment_date', models.CharField(max_length=20, verbose_name='评论日期')),
                ('user_name', models.CharField(max_length=20, verbose_name='评论者')),
                ('user_id', models.CharField(max_length=15, verbose_name='评论者id')),
            ],
            options={
                'verbose_name': '歌曲热评数据表',
                'verbose_name_plural': '歌曲热评数据表',
            },
        ),
    ]
