# Generated by Django 3.0.8 on 2020-08-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wy', '0002_database_head_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='head_link',
            field=models.CharField(default='', max_length=100, verbose_name='头像链接'),
        ),
    ]
