# Generated by Django 3.0.8 on 2020-08-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wy', '0003_auto_20200825_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='likedCount',
            field=models.CharField(default='', max_length=10, verbose_name='点赞数量'),
        ),
    ]
