# Generated by Django 3.0.8 on 2020-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wy', '0004_database_likedcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='singer_name',
            field=models.CharField(default='', max_length=20, verbose_name='歌手'),
        ),
        migrations.AlterField(
            model_name='database',
            name='likedCount',
            field=models.CharField(default='', max_length=20, verbose_name='点赞数量'),
        ),
        migrations.AlterField(
            model_name='database',
            name='song_id',
            field=models.CharField(max_length=20, verbose_name='歌曲id'),
        ),
        migrations.AlterField(
            model_name='database',
            name='user_id',
            field=models.CharField(max_length=20, verbose_name='评论者id'),
        ),
    ]
